"""Seed job roles for employee management

Revision ID: a823a6592a97
Revises: cbd059abd42d
Create Date: 2025-07-03 00:08:15.751347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a823a6592a97'
down_revision: Union[str, None] = 'cbd059abd42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    # Seed job roles for employee management
    connection = op.get_bind()
    
    # Check if job roles already exist to avoid duplicates
    existing_roles = connection.execute(
        sa.text("SELECT role_name FROM job_roles WHERE role_name IN ('maid', 'office', 'reception', 'maintenance', 'management')")
    ).fetchall()
    existing_role_names = [row[0] for row in existing_roles]
    
    # Define job roles to insert
    job_roles = [
        {
            'role_name': 'maid',
            'display_name': 'Maid',
            'description': 'Housekeeping and cleaning services',
            'has_shifts': False,
            'is_active': True
        },
        {
            'role_name': 'office',
            'display_name': 'Office',
            'description': 'General office and administrative work',
            'has_shifts': False,
            'is_active': True
        },
        {
            'role_name': 'reception',
            'display_name': 'Reception',
            'description': 'Front desk and customer service (with shifts)',
            'has_shifts': True,
            'is_active': True
        },
        {
            'role_name': 'maintenance',
            'display_name': 'Maintenance',
            'description': 'Building and equipment maintenance',
            'has_shifts': False,
            'is_active': True
        },
        {
            'role_name': 'management',
            'display_name': 'Management',
            'description': 'Supervisory and leadership roles',
            'has_shifts': False,
            'is_active': True
        }
    ]
    
    # Insert only new job roles
    for role in job_roles:
        if role['role_name'] not in existing_role_names:
            connection.execute(
                sa.text("""
                    INSERT INTO job_roles (role_name, display_name, description, has_shifts, is_active, created_at, updated_at)
                    VALUES (:role_name, :display_name, :description, :has_shifts, :is_active, datetime('now'), datetime('now'))
                """),
                role
            )
    
    connection.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    # Remove seeded job roles
    connection = op.get_bind()
    connection.execute(
        sa.text("DELETE FROM job_roles WHERE role_name IN ('maid', 'office', 'reception', 'maintenance', 'management')")
    )
    connection.commit()
